alter table TRAINING_CAR_SERVICE_CENTER add constraint FK_TRAINING_CAR_SERVICE_CENTER_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
create index IDX_TRAINING_CAR_SERVICE_CENTER_OWNER on TRAINING_CAR_SERVICE_CENTER (OWNER_ID);
