-- begin TRAINING_CITY
create unique index IDX_TRAINING_CITY_UNIQ_CODE on TRAINING_CITY (CODE) ^
create unique index IDX_TRAINING_CITY_UNIQ_NAME on TRAINING_CITY (NAME) ^
-- end TRAINING_CITY
-- begin TRAINING_CAR_SERVICE_CENTER
alter table TRAINING_CAR_SERVICE_CENTER add constraint FK_TRAINING_CAR_SERVICE_CENTER_CITY foreign key (CITY_ID) references TRAINING_CITY(ID)^
alter table TRAINING_CAR_SERVICE_CENTER add constraint FK_TRAINING_CAR_SERVICE_CENTER_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
create unique index IDX_TRAINING_CAR_SERVICE_CENTER_UNIQ_NAME on TRAINING_CAR_SERVICE_CENTER (NAME) ^
create index IDX_TRAINING_CAR_SERVICE_CENTER_CITY on TRAINING_CAR_SERVICE_CENTER (CITY_ID)^
create index IDX_TRAINING_CAR_SERVICE_CENTER_OWNER on TRAINING_CAR_SERVICE_CENTER (OWNER_ID)^
-- end TRAINING_CAR_SERVICE_CENTER
-- begin TRAINING_INDIVIDUAL
alter table TRAINING_INDIVIDUAL add constraint FK_TRAINING_INDIVIDUAL_ID foreign key (ID) references TRAINING_CUSTOMER(ID)^
-- end TRAINING_INDIVIDUAL
-- begin TRAINING_COMPANY
alter table TRAINING_COMPANY add constraint FK_TRAINING_COMPANY_ID foreign key (ID) references TRAINING_CUSTOMER(ID)^
-- end TRAINING_COMPANY
-- begin TRAINING_EMPLOYEE
alter table TRAINING_EMPLOYEE add constraint FK_TRAINING_EMPLOYEE_CENTER foreign key (CENTER_ID) references TRAINING_CAR_SERVICE_CENTER(ID)^
create index IDX_TRAINING_EMPLOYEE_CENTER on TRAINING_EMPLOYEE (CENTER_ID)^
-- end TRAINING_EMPLOYEE
-- begin TRAINING_REPAIR
alter table TRAINING_REPAIR add constraint FK_TRAINING_REPAIR_EMPLOYEE foreign key (EMPLOYEE_ID) references TRAINING_EMPLOYEE(ID)^
alter table TRAINING_REPAIR add constraint FK_TRAINING_REPAIR_CENTER foreign key (CENTER_ID) references TRAINING_CAR_SERVICE_CENTER(ID)^
alter table TRAINING_REPAIR add constraint FK_TRAINING_REPAIR_CUSTOMER foreign key (CUSTOMER_ID) references TRAINING_CUSTOMER(ID)^
create index IDX_TRAINING_REPAIR_EMPLOYEE on TRAINING_REPAIR (EMPLOYEE_ID)^
create index IDX_TRAINING_REPAIR_CUSTOMER on TRAINING_REPAIR (CUSTOMER_ID)^
create index IDX_TRAINING_REPAIR_CENTER on TRAINING_REPAIR (CENTER_ID)^
-- end TRAINING_REPAIR
-- begin TRAINING_CUSTOMER_CAR_SERVICE_CENTER_LINK
alter table TRAINING_CUSTOMER_CAR_SERVICE_CENTER_LINK add constraint FK_TCCSCL_CUSTOMER foreign key (CUSTOMER_ID) references TRAINING_CUSTOMER(ID)^
alter table TRAINING_CUSTOMER_CAR_SERVICE_CENTER_LINK add constraint FK_TCCSCL_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references TRAINING_CAR_SERVICE_CENTER(ID)^
-- end TRAINING_CUSTOMER_CAR_SERVICE_CENTER_LINK
